//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.load.data.entities.id;

import com.mei.ergosurgeon.load.business.utils.KafkaTemplatesUtil;
import com.mei.ergosurgeon.load.data.rules.AbstractKafkaTopic;
import org.apache.avro.specific.SpecificRecord;
import org.springframework.kafka.core.KafkaTemplate;

public class Client extends AbstractKafkaTopic {
    private Long timeStart;

    private Long timeEnd;

    public Client setTimeStart(Long timeStart) {
        this.timeStart = timeStart;
        return this;
    }

    public Client setTimeEnd(Long timeEnd) {
        this.timeEnd = timeEnd;
        return this;
    }

    @Override
    public String getTopic() {
        return "client";
    }

    @Override
    public KafkaTemplate<Object, Client> getKafkaTemplate() {
        return KafkaTemplatesUtil.getKafkaClientTemplate();
    }

    @Override
    public <T extends SpecificRecord> Class<T> mappingClass() {
        return (Class<T>) com.mei.ergosurgeon.schema.entities.Client.class;
    }
}
