//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.crud.data.entities;

import com.mei.ergosurgeon.crud.data.entities.custom.Key;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.*;


@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "joint")
@Table(name = "Joint")
public class Joint extends Key {

    @XmlElement(required = true)
    protected String connector1;

    @XmlElement(required = true)
    protected String connector2;

    @XmlAttribute(name = "label", required = true)
    protected String label;

    public String getConnector1() {
        return connector1;
    }

    public void setConnector1(String value) {
        this.connector1 = value;
    }

    public String getConnector2() {
        return connector2;
    }

    public void setConnector2(String value) {
        this.connector2 = value;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String value) {
        this.label = value;
    }

    public void process() {
        connector1 = connector1.split("\\/")[0];
        connector2 = connector2.split("\\/")[0];
    }
}
