//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.crud.data.entities;

import com.mei.ergosurgeon.crud.data.entities.custom.Key;

import javax.persistence.*;
import javax.xml.bind.annotation.*;

@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "mvnx")
@Table(name = "Mvnx")
public class Mvnx extends Key {

    @OneToOne(cascade = CascadeType.ALL)
    @XmlElement(required = true)
    protected Mvn mvn;

    @XmlElement(required = true)
    protected String comment;

    @OneToOne(cascade = CascadeType.ALL)
    @XmlElement(required = true)
    protected Subject subject;

    @Transient
    @XmlElement(required = true)
    protected SecurityCode securityCode;

    @XmlAttribute(name = "version", required = true)
    protected String version;

    public Mvn getMvn() {
        return mvn;
    }

    public void setMvn(Mvn value) {
        this.mvn = value;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String value) {
        this.comment = value;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject value) {
        this.subject = value;
    }

    public SecurityCode getSecurityCode() {
        return securityCode;
    }

    public void setSecurityCode(SecurityCode value) {
        this.securityCode = value;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String value) {
        this.version = value;
    }

    public Mvnx process() {
        getSubject().process();
        return this;
    }
}
