//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.crud.data.entities;

import com.mei.ergosurgeon.crud.data.entities.custom.Key;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.ArrayList;
import java.util.List;


@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "segments")
@Table(name = "Segments")
public class Segments extends Key {

    @OneToMany(cascade = CascadeType.ALL)
    @XmlElement(required = true)
    protected List<Segment> segment;

    public List<Segment> getSegment() {
        if (segment == null) {
            segment = new ArrayList<Segment>();
        }
        return this.segment;
    }

    public void process() {
        getSegment().parallelStream().forEach(item -> item.process());
    }
}
