//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.crud.data.entities;

import com.mei.ergosurgeon.crud.data.entities.custom.Key;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.*;
import java.math.BigInteger;

@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "subject")
@Table(name = "Subject")
public class Subject extends Key {


    @XmlElement(required = true)
    protected String comment;

    @OneToOne(cascade = CascadeType.ALL)
    @XmlElement(required = true)
    protected Segments segments;

    @OneToOne(cascade = CascadeType.ALL)
    protected Sensors sensors;

    @OneToOne(cascade = CascadeType.ALL)
    protected Joints joints;

    @OneToOne(cascade = CascadeType.ALL)
    @XmlElement(required = true)
    protected Frames frames;

    @XmlAttribute(name = "label", required = true)
    protected String label;

    @XmlAttribute(name = "torsoColor", required = true)
    protected String torsoColor;

    @XmlAttribute(name = "frameRate", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger frameRate;

    @XmlAttribute(name = "segmentCount", required = true)
    protected String segmentCount;

    @XmlAttribute(name = "recDate", required = true)
    protected String recDate;

    @XmlAttribute(name = "originalFilename", required = true)
    protected String originalFilename;

    public String getComment() {
        return comment;
    }

    public void setComment(String value) {
        this.comment = value;
    }

    public Segments getSegments() {
        return segments;
    }

    public void setSegments(Segments value) {
        this.segments = value;
    }

    public Sensors getSensors() {
        return sensors;
    }

    public void setSensors(Sensors value) {
        this.sensors = value;
    }

    public Joints getJoints() {
        return joints;
    }

    public void setJoints(Joints value) {
        this.joints = value;
    }

    public Frames getFrames() {
        return frames;
    }

    public void setFrames(Frames value) {
        this.frames = value;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String value) {
        this.label = value;
    }

    public String getTorsoColor() {
        return torsoColor;
    }

    public void setTorsoColor(String value) {
        this.torsoColor = value;
    }

    public BigInteger getFrameRate() {
        return frameRate;
    }

    public void setFrameRate(BigInteger value) {
        this.frameRate = value;
    }

    public String getSegmentCount() {
        return segmentCount;
    }

    public void setSegmentCount(String value) {
        this.segmentCount = value;
    }

    public String getRecDate() {
        return recDate;
    }

    public void setRecDate(String value) {
        this.recDate = value;
    }

    public String getOriginalFilename() {
        return originalFilename;
    }

    public void setOriginalFilename(String value) {
        this.originalFilename = value;
    }

    public void process() {
        getSegments().process();
        getJoints().process();
        getFrames().process();
        getSensors().process();
    }

    @Override
    public String toString() {
        return "Subject{" +
                "comment='" + comment + '\'' +
                ", segments=" + segments +
                ", sensors=" + sensors +
                ", joints=" + joints +
                ", frames=" + frames +
                ", label='" + label + '\'' +
                ", torsoColor='" + torsoColor + '\'' +
                ", frameRate=" + frameRate +
                ", segmentCount='" + segmentCount + '\'' +
                ", recDate='" + recDate + '\'' +
                ", originalFilename='" + originalFilename + '\'' +
                '}';
    }
}
