spring:
  kafka:
    bootstrap-servers: 35.239.50.117:9093,35.224.106.50:9093,34.66.142.32:9093
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      transaction-id-prefix: tx.
      retries: 10
    properties:
      schema.registry.url: http://34.70.1.18:8081
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="puFoL6iRENSS";
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB

logging:
  level:
    root: INFO




## Because detection is disabled you have to set correct dialect by hand.
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
#spring.data.cassandra.cluster-name=cassandra-cluster
#spring.data.cassandra.=ergosurgeon
#spring.data.cassandra.keyspace-name=ergosurgeon
#spring.data.cassandra.port=9042
#spring.data.cassandra.contact-points=localhost
#spring.data.cassandra.schema-action=create_if_not_exists
#spring.data.cassandra.password=cassandra
#spring.data.cassandra.username=cassandra

