//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.load.data.entities;


import com.mei.ergosurgeon.load.business.api.KafkaLoadService;
import com.mei.ergosurgeon.load.business.utils.KafkaTemplatesUtil;
import com.mei.ergosurgeon.load.data.entities.id.Client;
import com.mei.ergosurgeon.load.data.rules.AbstractKafkaTopic;
import com.mei.ergosurgeon.load.data.rules.TopicFather;
import org.springframework.kafka.core.KafkaTemplate;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "frames")
public class Frames extends AbstractKafkaTopic implements TopicFather
// By itself this configuration represent 1 -> 1 || N
// (By the current solution, another approaches change automatically that.)
{
    @XmlElement(required = true)
    protected List<Frame> frame;

    @XmlAttribute(name = "segmentCount", required = true)
    protected String segmentCount;

    @XmlAttribute(name = "sensorCount")
    protected String sensorCount;

    @XmlAttribute(name = "jointCount")
    protected String jointCount;

    public List<Frame> getFrame() {
        if (frame == null) {
            frame = new ArrayList<Frame>();
        }
        return this.frame;
    }

    public String getSegmentCount() {
        return segmentCount;
    }

    public void setSegmentCount(String value) {
        this.segmentCount = value;
    }

    public String getSensorCount() {
        return sensorCount;
    }

    public void setSensorCount(String value) {
        this.sensorCount = value;
    }

    public String getJointCount() {
        return jointCount;
    }

    public void setJointCount(String value) {
        this.jointCount = value;
    }

    @Override
    public void send(KafkaLoadService proxy, Client client) throws Exception {
        proxy.send(this, com.mei.ergosurgeon.schema.entities.Frames.class, client);
    }

    @Override
    public String getTopic() {
        return "frames";
    }

    @Override
    public KafkaTemplate<Object, Frames> getKafkaTemplate() {
        return KafkaTemplatesUtil.getKafkaFramesTemplate();
    }

    @Override
    public void process(KafkaLoadService proxy, Client client) throws Exception {
        process(proxy, client, getFrame());
    }
}
