//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.load.data.entities;

import com.mei.ergosurgeon.load.business.api.KafkaLoadService;
import com.mei.ergosurgeon.load.business.utils.AvroFilesUtil;
import com.mei.ergosurgeon.load.business.utils.KafkaTemplatesUtil;
import com.mei.ergosurgeon.load.data.entities.custom.KafkaTopic;
import org.springframework.kafka.core.KafkaTemplate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.File;

import static com.mei.ergosurgeon.load.common.IlegalStateExceptionEnum.AVRO_INDEX_RECORD_GET;
import static com.mei.ergosurgeon.load.common.IlegalStateExceptionEnum.AVRO_INDEX_RECORD_PUT;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "mvn")
public class Mvn implements KafkaTopic<Mvn> {

    @XmlAttribute(name = "version", required = true)
    protected String version;

    @XmlAttribute(name = "build", required = true)
    protected String build;

    public String getVersion() {
        return version;
    }

    public void setVersion(String value) {
        this.version = value;
    }

    public String getBuild() {
        return build;
    }

    public void setBuild(String value) {
        this.build = value;
    }

    @Override
    public Mvn process(KafkaLoadService proxy) throws Exception {

        proxy.send(this);
        return this;
    }

    @Override
    public String getTopic() {
        return "mvn";
    }


    @Override
    public KafkaTemplate<Object, Mvn> getKafkaTemplate() {
        return KafkaTemplatesUtil.getKafkaMvnTemplate();
    }

    @Override
    public File getAvroSchemaFile() {
        return AvroFilesUtil.getAvroMvnSchema();
    }

    @Override
    public void put(int i, Object v) {
        switch (i) {
            case 0:
                setVersion((String) v);
                break;
            case 1:
                setBuild((String) v);
                break;
            default:
                throw new IllegalStateException(AVRO_INDEX_RECORD_PUT.getValue());

        }
    }

    @Override
    public Object get(int i) {
        switch (i) {
            case 0:
                return getVersion();
            case 1:
                return getBuild();
            default:
                throw new IllegalStateException(AVRO_INDEX_RECORD_GET.getValue());
        }
    }
}
