//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.load.data.entities;

import com.mei.ergosurgeon.load.business.api.KafkaLoadService;
import com.mei.ergosurgeon.load.business.utils.KafkaTemplatesUtil;
import com.mei.ergosurgeon.load.data.entities.custom.Client;
import com.mei.ergosurgeon.load.data.rules.AbstractKafkaTopic;
import com.mei.ergosurgeon.load.data.rules.KafkaTopic;
import org.springframework.kafka.core.KafkaTemplate;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "mvnx")
public class Mvnx extends AbstractKafkaTopic<Mvnx> {

    @XmlElement(required = true)
    protected Mvn mvn;

    @XmlElement(required = true)
    protected String comment;

    @XmlElement(required = true)
    protected Subject subject;

    @XmlElement(required = true)
    protected SecurityCode securityCode;

    @XmlAttribute(name = "version", required = true)
    protected String version;

    public Mvn getMvn() {
        return mvn;
    }

    public void setMvn(Mvn value) {
        this.mvn = value;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String value) {
        this.comment = value;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject value) {
        this.subject = value;
    }

    public SecurityCode getSecurityCode() {
        return securityCode;
    }

    public void setSecurityCode(SecurityCode value) {
        this.securityCode = value;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String value) {
        this.version = value;
    }

    public Mvnx send(KafkaLoadService proxy, Client client) throws Exception {
        proxy.send(this, com.mei.ergosurgeon.schema.entities.Mvnx.class, client);
        getSubject().send(proxy, client);
        getMvn().send(proxy, client);
        return this;
    }

    @Override
    public String getTopic() {
        return "mvnx";
    }


    @Override
    public KafkaTemplate<Object, Mvnx> getKafkaTemplate() {
        return KafkaTemplatesUtil.getKafkaMvnxTemplate();
    }
}
