//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.load.data.entities;

import com.mei.ergosurgeon.load.business.AvroFiles;
import com.mei.ergosurgeon.load.business.KafkaTemplates;
import com.mei.ergosurgeon.load.data.entities.custom.KafkaTopic;
import org.springframework.kafka.core.KafkaTemplate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.File;
import java.util.ArrayList;
import java.util.List;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "points")
public class Points implements KafkaTopic<Points> {

    @XmlElement(required = true)
    protected List<Point> point;

    public List<Point> getPoint() {
        if (point == null) {
            point = new ArrayList<Point>();
        }
        return this.point;
    }

    public Points process() {
        getPoint().stream().forEach(item -> item.process());
        //send(this);
        return this;
    }

    @Override
    public String getTopic() {
        return "points";
    }


    @Override
    public KafkaTemplate<Object, Points> getKafkaTemplate() {
        return KafkaTemplates.getKafkaPointsTemplate();
    }

    @Override
    public File getAvroFile() {
        return AvroFiles.getAvroPointsSchema();
    }
}
