//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.load.data.entities;

import com.mei.ergosurgeon.load.business.AvroFiles;
import com.mei.ergosurgeon.load.business.KafkaTemplates;
import com.mei.ergosurgeon.load.data.entities.custom.KafkaTopic;
import org.springframework.kafka.core.KafkaTemplate;

import javax.xml.bind.annotation.*;
import java.io.File;
import java.math.BigInteger;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "segment")
public class Segment implements KafkaTopic<Segment> {

    @XmlElement(required = true)
    protected Points points;

    @XmlAttribute(name = "label", required = true)
    protected String label;

    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger segmentId;

    public Points getPoints() {
        return points;
    }

    public void setPoints(Points value) {
        this.points = value;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String value) {
        this.label = value;
    }

    public BigInteger getSegmentId() {
        return segmentId;
    }

    public void setSegmentId(BigInteger segmentId) {
        this.segmentId = segmentId;
    }

    public Segment process() {
        getPoints().process();
        //send(this);
        return this;
    }

    @Override
    public String getTopic() {
        return "segment";
    }

    @Override
    public KafkaTemplate<Object, Segment> getKafkaTemplate() {
        return KafkaTemplates.getKafkaSegmentTemplate();
    }

    @Override
    public File getAvroFile() {
        return AvroFiles.getAvroSegmentSchema();
    }
}
