spring:
  kafka:
    bootstrap-servers: 34.65.62.56:9092,34.65.208.54:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      transaction-id-prefix: tx.
      retries: 10
    properties:
      schema.registry.url: http://35.193.178.156:8081
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="NuhwSBK7d5t8";
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB


logging:
  level:
    root: INFO



## Because detection is disabled you have to set correct dialect by hand.
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
#spring.data.cassandra.cluster-name=cassandra-cluster
#spring.data.cassandra.=ergosurgeon
#spring.data.cassandra.keyspace-name=ergosurgeon
#spring.data.cassandra.port=9042
#spring.data.cassandra.contact-points=localhost
#spring.data.cassandra.schema-action=create_if_not_exists
#spring.data.cassandra.password=cassandra
#spring.data.cassandra.username=cassandra

