/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.mei.ergosurgeon.schema.entities.custom;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Quaternion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Quaternion\",\"namespace\":\"com.mei.ergosurgeon.schema.entities.custom\",\"fields\":[{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"q0\",\"type\":\"float\"},{\"name\":\"q1\",\"type\":\"float\"},{\"name\":\"q2\",\"type\":\"float\"},{\"name\":\"q3\",\"type\":\"float\"},{\"name\":\"segmentLabel\",\"type\":\"string\"}]}");
    private static final long serialVersionUID = -3419672651634858944L;
    private static SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<Quaternion> ENCODER =
            new BinaryMessageEncoder<Quaternion>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<Quaternion> DECODER =
            new BinaryMessageDecoder<Quaternion>(MODEL$, SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<Quaternion>
            WRITER$ = (org.apache.avro.io.DatumWriter<Quaternion>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<Quaternion>
            READER$ = (org.apache.avro.io.DatumReader<Quaternion>) MODEL$.createDatumReader(SCHEMA$);
    @Deprecated
    public long time;
    @Deprecated
    public float q0;
    @Deprecated
    public float q1;
    @Deprecated
    public float q2;
    @Deprecated
    public float q3;
    @Deprecated
    public java.lang.CharSequence segmentLabel;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public Quaternion() {
    }

    /**
     * All-args constructor.
     * @param time The new value for time
     * @param q0 The new value for q0
     * @param q1 The new value for q1
     * @param q2 The new value for q2
     * @param q3 The new value for q3
     * @param segmentLabel The new value for segmentLabel
     */
    public Quaternion(java.lang.Long time, java.lang.Float q0, java.lang.Float q1, java.lang.Float q2, java.lang.Float q3, java.lang.CharSequence segmentLabel) {
        this.time = time;
        this.q0 = q0;
        this.q1 = q1;
        this.q2 = q2;
        this.q3 = q3;
        this.segmentLabel = segmentLabel;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     */
    public static BinaryMessageDecoder<Quaternion> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     */
    public static BinaryMessageDecoder<Quaternion> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<Quaternion>(MODEL$, SCHEMA$, resolver);
    }

    /** Deserializes a Quaternion from a ByteBuffer. */
    public static Quaternion fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new Quaternion RecordBuilder.
     * @return A new Quaternion RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder newBuilder() {
        return new com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder();
    }

    /**
     * Creates a new Quaternion RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new Quaternion RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder newBuilder(com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder other) {
        return new com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder(other);
    }

    /**
     * Creates a new Quaternion RecordBuilder by copying an existing Quaternion instance.
     * @param other The existing instance to copy.
     * @return A new Quaternion RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder newBuilder(com.mei.ergosurgeon.schema.entities.custom.Quaternion other) {
        return new com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder(other);
    }

    /** Serializes this Quaternion to a ByteBuffer. */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return time;
            case 1:
                return q0;
            case 2:
                return q1;
            case 3:
                return q2;
            case 4:
                return q3;
            case 5:
                return segmentLabel;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                time = (java.lang.Long) value$;
                break;
            case 1:
                q0 = (java.lang.Float) value$;
                break;
            case 2:
                q1 = (java.lang.Float) value$;
                break;
            case 3:
                q2 = (java.lang.Float) value$;
                break;
            case 4:
                q3 = (java.lang.Float) value$;
                break;
            case 5:
                segmentLabel = (java.lang.CharSequence) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'time' field.
     * @return The value of the 'time' field.
     */
    public java.lang.Long getTime() {
        return time;
    }

    /**
     * Sets the value of the 'time' field.
     * @param value the value to set.
     */
    public void setTime(java.lang.Long value) {
        this.time = value;
    }

    /**
     * Gets the value of the 'q0' field.
     * @return The value of the 'q0' field.
     */
    public java.lang.Float getQ0() {
        return q0;
    }

    /**
     * Sets the value of the 'q0' field.
     * @param value the value to set.
     */
    public void setQ0(java.lang.Float value) {
        this.q0 = value;
    }

    /**
     * Gets the value of the 'q1' field.
     * @return The value of the 'q1' field.
     */
    public java.lang.Float getQ1() {
        return q1;
    }

    /**
     * Sets the value of the 'q1' field.
     * @param value the value to set.
     */
    public void setQ1(java.lang.Float value) {
        this.q1 = value;
    }

    /**
     * Gets the value of the 'q2' field.
     * @return The value of the 'q2' field.
     */
    public java.lang.Float getQ2() {
        return q2;
    }

    /**
     * Sets the value of the 'q2' field.
     * @param value the value to set.
     */
    public void setQ2(java.lang.Float value) {
        this.q2 = value;
    }

    /**
     * Gets the value of the 'q3' field.
     * @return The value of the 'q3' field.
     */
    public java.lang.Float getQ3() {
        return q3;
    }

    /**
     * Sets the value of the 'q3' field.
     * @param value the value to set.
     */
    public void setQ3(java.lang.Float value) {
        this.q3 = value;
    }

    /**
     * Gets the value of the 'segmentLabel' field.
     * @return The value of the 'segmentLabel' field.
     */
    public java.lang.CharSequence getSegmentLabel() {
        return segmentLabel;
    }

    /**
     * Sets the value of the 'segmentLabel' field.
     * @param value the value to set.
     */
    public void setSegmentLabel(java.lang.CharSequence value) {
        this.segmentLabel = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    /**
     * RecordBuilder for Quaternion instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Quaternion>
            implements org.apache.avro.data.RecordBuilder<Quaternion> {

        private long time;
        private float q0;
        private float q1;
        private float q2;
        private float q3;
        private java.lang.CharSequence segmentLabel;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.time)) {
                this.time = data().deepCopy(fields()[0].schema(), other.time);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.q0)) {
                this.q0 = data().deepCopy(fields()[1].schema(), other.q0);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.q1)) {
                this.q1 = data().deepCopy(fields()[2].schema(), other.q1);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.q2)) {
                this.q2 = data().deepCopy(fields()[3].schema(), other.q2);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.q3)) {
                this.q3 = data().deepCopy(fields()[4].schema(), other.q3);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.segmentLabel)) {
                this.segmentLabel = data().deepCopy(fields()[5].schema(), other.segmentLabel);
                fieldSetFlags()[5] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing Quaternion instance
         * @param other The existing instance to copy.
         */
        private Builder(com.mei.ergosurgeon.schema.entities.custom.Quaternion other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.time)) {
                this.time = data().deepCopy(fields()[0].schema(), other.time);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.q0)) {
                this.q0 = data().deepCopy(fields()[1].schema(), other.q0);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.q1)) {
                this.q1 = data().deepCopy(fields()[2].schema(), other.q1);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.q2)) {
                this.q2 = data().deepCopy(fields()[3].schema(), other.q2);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.q3)) {
                this.q3 = data().deepCopy(fields()[4].schema(), other.q3);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.segmentLabel)) {
                this.segmentLabel = data().deepCopy(fields()[5].schema(), other.segmentLabel);
                fieldSetFlags()[5] = true;
            }
        }

        /**
         * Gets the value of the 'time' field.
         * @return The value.
         */
        public java.lang.Long getTime() {
            return time;
        }

        /**
         * Sets the value of the 'time' field.
         * @param value The value of 'time'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder setTime(long value) {
            validate(fields()[0], value);
            this.time = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'time' field has been set.
         * @return True if the 'time' field has been set, false otherwise.
         */
        public boolean hasTime() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'time' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder clearTime() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'q0' field.
         * @return The value.
         */
        public java.lang.Float getQ0() {
            return q0;
        }

        /**
         * Sets the value of the 'q0' field.
         * @param value The value of 'q0'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder setQ0(float value) {
            validate(fields()[1], value);
            this.q0 = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'q0' field has been set.
         * @return True if the 'q0' field has been set, false otherwise.
         */
        public boolean hasQ0() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'q0' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder clearQ0() {
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'q1' field.
         * @return The value.
         */
        public java.lang.Float getQ1() {
            return q1;
        }

        /**
         * Sets the value of the 'q1' field.
         * @param value The value of 'q1'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder setQ1(float value) {
            validate(fields()[2], value);
            this.q1 = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'q1' field has been set.
         * @return True if the 'q1' field has been set, false otherwise.
         */
        public boolean hasQ1() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'q1' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder clearQ1() {
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'q2' field.
         * @return The value.
         */
        public java.lang.Float getQ2() {
            return q2;
        }

        /**
         * Sets the value of the 'q2' field.
         * @param value The value of 'q2'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder setQ2(float value) {
            validate(fields()[3], value);
            this.q2 = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'q2' field has been set.
         * @return True if the 'q2' field has been set, false otherwise.
         */
        public boolean hasQ2() {
            return fieldSetFlags()[3];
        }


        /**
         * Clears the value of the 'q2' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder clearQ2() {
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'q3' field.
         * @return The value.
         */
        public java.lang.Float getQ3() {
            return q3;
        }

        /**
         * Sets the value of the 'q3' field.
         * @param value The value of 'q3'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder setQ3(float value) {
            validate(fields()[4], value);
            this.q3 = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'q3' field has been set.
         * @return True if the 'q3' field has been set, false otherwise.
         */
        public boolean hasQ3() {
            return fieldSetFlags()[4];
        }


        /**
         * Clears the value of the 'q3' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder clearQ3() {
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'segmentLabel' field.
         * @return The value.
         */
        public java.lang.CharSequence getSegmentLabel() {
            return segmentLabel;
        }

        /**
         * Sets the value of the 'segmentLabel' field.
         * @param value The value of 'segmentLabel'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder setSegmentLabel(java.lang.CharSequence value) {
            validate(fields()[5], value);
            this.segmentLabel = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'segmentLabel' field has been set.
         * @return True if the 'segmentLabel' field has been set, false otherwise.
         */
        public boolean hasSegmentLabel() {
            return fieldSetFlags()[5];
        }


        /**
         * Clears the value of the 'segmentLabel' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.custom.Quaternion.Builder clearSegmentLabel() {
            segmentLabel = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public Quaternion build() {
            try {
                Quaternion record = new Quaternion();
                record.time = fieldSetFlags()[0] ? this.time : (java.lang.Long) defaultValue(fields()[0]);
                record.q0 = fieldSetFlags()[1] ? this.q0 : (java.lang.Float) defaultValue(fields()[1]);
                record.q1 = fieldSetFlags()[2] ? this.q1 : (java.lang.Float) defaultValue(fields()[2]);
                record.q2 = fieldSetFlags()[3] ? this.q2 : (java.lang.Float) defaultValue(fields()[3]);
                record.q3 = fieldSetFlags()[4] ? this.q3 : (java.lang.Float) defaultValue(fields()[4]);
                record.segmentLabel = fieldSetFlags()[5] ? this.segmentLabel : (java.lang.CharSequence) defaultValue(fields()[5]);
                return record;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

}
