//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 11:20:22 PM BST 
//


package com.mei.ergosurgeon.load.data.entities.custom;

import com.mei.ergosurgeon.load.business.api.KafkaLoadService;
import com.mei.ergosurgeon.load.business.utils.KafkaTemplatesUtil;
import org.springframework.kafka.core.KafkaTemplate;

public class Client implements KafkaTopic<Client> {

    private Integer id;

    private String uuid;

    private String email;

    private Long timeStart;

    private Long timeEnd;

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public Client setUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    public Client setEmail(String email) {
        this.email = email;
        return this;
    }

    public Client setTimeStart(Long timeStart) {
        this.timeStart = timeStart;
        return this;
    }

    public Client setTimeEnd(Long timeEnd) {
        this.timeEnd = timeEnd;
        return this;
    }

    public Client send(KafkaLoadService proxy, Client client) throws Exception {

        proxy.send(this, com.mei.ergosurgeon.schema.entities.Client.class, client);
        return this;
    }

    @Override
    public String getTopic() {
        return "client";
    }

    @Override
    public KafkaTemplate<Object, Client> getKafkaTemplate() {
        return KafkaTemplatesUtil.getKafkaClientTemplate();
    }
}
