/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.mei.ergosurgeon.schema.entities;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Mvn extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Mvn\",\"namespace\":\"com.mei.ergosurgeon.schema.entities\",\"fields\":[{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"build\",\"type\":\"string\"}]}");
    private static final long serialVersionUID = -6172323147154041442L;
    private static SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<Mvn> ENCODER =
            new BinaryMessageEncoder<Mvn>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<Mvn> DECODER =
            new BinaryMessageDecoder<Mvn>(MODEL$, SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<Mvn>
            WRITER$ = (org.apache.avro.io.DatumWriter<Mvn>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<Mvn>
            READER$ = (org.apache.avro.io.DatumReader<Mvn>) MODEL$.createDatumReader(SCHEMA$);
    @Deprecated
    public java.lang.CharSequence version;
    @Deprecated
    public java.lang.CharSequence build;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public Mvn() {
    }

    /**
     * All-args constructor.
     * @param version The new value for version
     * @param build The new value for build
     */
    public Mvn(java.lang.CharSequence version, java.lang.CharSequence build) {
        this.version = version;
        this.build = build;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     */
    public static BinaryMessageDecoder<Mvn> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     */
    public static BinaryMessageDecoder<Mvn> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<Mvn>(MODEL$, SCHEMA$, resolver);
    }

    /** Deserializes a Mvn from a ByteBuffer. */
    public static Mvn fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new Mvn RecordBuilder.
     * @return A new Mvn RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.Mvn.Builder newBuilder() {
        return new com.mei.ergosurgeon.schema.entities.Mvn.Builder();
    }

    /**
     * Creates a new Mvn RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new Mvn RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.Mvn.Builder newBuilder(com.mei.ergosurgeon.schema.entities.Mvn.Builder other) {
        return new com.mei.ergosurgeon.schema.entities.Mvn.Builder(other);
    }

    /**
     * Creates a new Mvn RecordBuilder by copying an existing Mvn instance.
     * @param other The existing instance to copy.
     * @return A new Mvn RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.Mvn.Builder newBuilder(com.mei.ergosurgeon.schema.entities.Mvn other) {
        return new com.mei.ergosurgeon.schema.entities.Mvn.Builder(other);
    }

    /** Serializes this Mvn to a ByteBuffer. */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return version;
            case 1:
                return build;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                version = (java.lang.CharSequence) value$;
                break;
            case 1:
                build = (java.lang.CharSequence) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'version' field.
     * @return The value of the 'version' field.
     */
    public java.lang.CharSequence getVersion() {
        return version;
    }

    /**
     * Sets the value of the 'version' field.
     * @param value the value to set.
     */
    public void setVersion(java.lang.CharSequence value) {
        this.version = value;
    }

    /**
     * Gets the value of the 'build' field.
     * @return The value of the 'build' field.
     */
    public java.lang.CharSequence getBuild() {
        return build;
    }

    /**
     * Sets the value of the 'build' field.
     * @param value the value to set.
     */
    public void setBuild(java.lang.CharSequence value) {
        this.build = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    /**
     * RecordBuilder for Mvn instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Mvn>
            implements org.apache.avro.data.RecordBuilder<Mvn> {

        private java.lang.CharSequence version;
        private java.lang.CharSequence build;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.mei.ergosurgeon.schema.entities.Mvn.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.version)) {
                this.version = data().deepCopy(fields()[0].schema(), other.version);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.build)) {
                this.build = data().deepCopy(fields()[1].schema(), other.build);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing Mvn instance
         * @param other The existing instance to copy.
         */
        private Builder(com.mei.ergosurgeon.schema.entities.Mvn other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.version)) {
                this.version = data().deepCopy(fields()[0].schema(), other.version);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.build)) {
                this.build = data().deepCopy(fields()[1].schema(), other.build);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'version' field.
         * @return The value.
         */
        public java.lang.CharSequence getVersion() {
            return version;
        }

        /**
         * Sets the value of the 'version' field.
         * @param value The value of 'version'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.Mvn.Builder setVersion(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.version = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'version' field has been set.
         * @return True if the 'version' field has been set, false otherwise.
         */
        public boolean hasVersion() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'version' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.Mvn.Builder clearVersion() {
            version = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'build' field.
         * @return The value.
         */
        public java.lang.CharSequence getBuild() {
            return build;
        }

        /**
         * Sets the value of the 'build' field.
         * @param value The value of 'build'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.Mvn.Builder setBuild(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.build = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'build' field has been set.
         * @return True if the 'build' field has been set, false otherwise.
         */
        public boolean hasBuild() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'build' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.Mvn.Builder clearBuild() {
            build = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public Mvn build() {
            try {
                Mvn record = new Mvn();
                record.version = fieldSetFlags()[0] ? this.version : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.build = fieldSetFlags()[1] ? this.build : (java.lang.CharSequence) defaultValue(fields()[1]);
                return record;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

}
