spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      #To register all Registering MessageChannel by monitor.IntegrationMBeanExporter
      bindings:
        default:
          contentType: application/*+avro
        input:
          destination: raw_point
          group: process
        output:
          destination: threated_point
          group: process
      #Config do stream do spring kafka   # Without !!! Cannot convert from [[B] to [com.mei.ergosurgeon.process.data.entities.Point]
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://34.77.193.220:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://34.77.193.220:8081
            specific.avro.reader: true
          required-acks: all
          transaction:
            transaction-id-prefix: tx.
          replication-factor: 1
  #Prperties of Kafka-clients
  kafka:
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="t3EhuxADmC2J";
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    producer:
      transaction-id-prefix: tx.
      acks: all
      retries: 10

    consumer:
      group-id: process
    bootstrap-servers: 34.90.183.51:9092,35.204.239.208:9092,35.204.122.190:9092
    streams:
      replication-factor: 3

logging:
  level:
    root: INFO


