spring:
  cloud:
    gcp:
      credentials:
        #Diferent environments 1- local 2- cloud
        location: file:src/main/resources/postgresGcp.json
        #location: file:WEB-INF/classes/postgresGcp.json
      config:
        project-id: ergosurgeon
      sql:
        database-name: ergosurgeon
        instance-connection-name: ergosurgeon:europe-west3:ergosurgeon-postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false

  datasource:
    username: postgres
    password: postgres
    continue-on-error: false
    initialization-mode: always

logging:
  level:
    root: INFO