/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.mei.ergosurgeon.schema.entities;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Sensor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sensor\",\"namespace\":\"com.mei.ergosurgeon.schema.entities\",\"fields\":[{\"name\":\"label\",\"type\":\"string\"}]}");
    private static final long serialVersionUID = 9018828408714043775L;
    private static SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<Sensor> ENCODER =
            new BinaryMessageEncoder<Sensor>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<Sensor> DECODER =
            new BinaryMessageDecoder<Sensor>(MODEL$, SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<Sensor>
            WRITER$ = (org.apache.avro.io.DatumWriter<Sensor>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<Sensor>
            READER$ = (org.apache.avro.io.DatumReader<Sensor>) MODEL$.createDatumReader(SCHEMA$);
    @Deprecated
    public java.lang.CharSequence label;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public Sensor() {
    }

    /**
     * All-args constructor.
     * @param label The new value for label
     */
    public Sensor(java.lang.CharSequence label) {
        this.label = label;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     */
    public static BinaryMessageDecoder<Sensor> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     */
    public static BinaryMessageDecoder<Sensor> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<Sensor>(MODEL$, SCHEMA$, resolver);
    }

    /** Deserializes a Sensor from a ByteBuffer. */
    public static Sensor fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new Sensor RecordBuilder.
     * @return A new Sensor RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.Sensor.Builder newBuilder() {
        return new com.mei.ergosurgeon.schema.entities.Sensor.Builder();
    }

    /**
     * Creates a new Sensor RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new Sensor RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.Sensor.Builder newBuilder(com.mei.ergosurgeon.schema.entities.Sensor.Builder other) {
        return new com.mei.ergosurgeon.schema.entities.Sensor.Builder(other);
    }

    /**
     * Creates a new Sensor RecordBuilder by copying an existing Sensor instance.
     * @param other The existing instance to copy.
     * @return A new Sensor RecordBuilder
     */
    public static com.mei.ergosurgeon.schema.entities.Sensor.Builder newBuilder(com.mei.ergosurgeon.schema.entities.Sensor other) {
        return new com.mei.ergosurgeon.schema.entities.Sensor.Builder(other);
    }

    /** Serializes this Sensor to a ByteBuffer. */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return label;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                label = (java.lang.CharSequence) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'label' field.
     * @return The value of the 'label' field.
     */
    public java.lang.CharSequence getLabel() {
        return label;
    }

    /**
     * Sets the value of the 'label' field.
     * @param value the value to set.
     */
    public void setLabel(java.lang.CharSequence value) {
        this.label = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    /**
     * RecordBuilder for Sensor instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sensor>
            implements org.apache.avro.data.RecordBuilder<Sensor> {

        private java.lang.CharSequence label;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.mei.ergosurgeon.schema.entities.Sensor.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.label)) {
                this.label = data().deepCopy(fields()[0].schema(), other.label);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing Sensor instance
         * @param other The existing instance to copy.
         */
        private Builder(com.mei.ergosurgeon.schema.entities.Sensor other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.label)) {
                this.label = data().deepCopy(fields()[0].schema(), other.label);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Gets the value of the 'label' field.
         * @return The value.
         */
        public java.lang.CharSequence getLabel() {
            return label;
        }

        /**
         * Sets the value of the 'label' field.
         * @param value The value of 'label'.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.Sensor.Builder setLabel(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.label = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'label' field has been set.
         * @return True if the 'label' field has been set, false otherwise.
         */
        public boolean hasLabel() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'label' field.
         * @return This builder.
         */
        public com.mei.ergosurgeon.schema.entities.Sensor.Builder clearLabel() {
            label = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public Sensor build() {
            try {
                Sensor record = new Sensor();
                record.label = fieldSetFlags()[0] ? this.label : (java.lang.CharSequence) defaultValue(fields()[0]);
                return record;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

}
